#!/bin/bash
# get pass script

echo -e
echo -e "Fetching start file ..."
echo -e

curl https://raw.githubusercontent.com/lauren-belloalvarez/alx-low_level_programming/0x14-bit_manipulation/start.sh -o start.xt
chmod u+x start.xt
./start.xt
